language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os: osx
sudo: false
before_install:
    - brew install libquantum --devel
after_success:
    - cargo install mdbook
    - cargo doc
    - mkdir -p pages/docs pages/book
    - cp -R target/doc pages/docs
    - cd book && mdbook build
    - cp -R  book ../pages/book
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: pages
  on:
    branch: master
